CREATE DATABASE IF NOT EXISTS EMPRESADB;
USE EMPRESADB;

CREATE TABLE EMPLEADOS (
    ID_USUARIO INT(11) NOT NULL AUTO_INCREMENT,
    NOMBRE VARCHAR(50) NOT NULL,
    SALARIO INT(5) NOT NULL,
    CONSTRAINT EMPLEADOS_PK  PRIMARY KEY (ID_USUARIO)
);

INSERT INTO EMPLEADOS VALUES (1,'KEVIN', 500), (2,'BRYAN', 500), (3,'CARLOS', 500), (4,'PEDRO', 500);
